[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade || true",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "python main.py"
