[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel"
]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/python -m pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python main.py"
